import { $TSAny } from 'amplify-cli-core';
import { Context } from './context';
export declare class AmplifyToolkit {
  private _confirmPrompt;
  private _constants;
  private _constructExeInfo;
  private _copyBatch;
  private _crudFlow;
  private _deleteProject;
  private _executeProviderUtils;
  private _getAllEnvs;
  private _getPlugin;
  private _getCategoryPluginInfo;
  private _getAllCategoryPluginInfo;
  private _getFrontendPlugins;
  private _getEnvDetails;
  private _getEnvInfo?;
  private _getProviderPlugins;
  private _getPluginInstance;
  private _getProjectConfig;
  private _getProjectDetails?;
  private _getProjectMeta?;
  private _getResourceStatus;
  private _getResourceOutputs;
  private _getWhen;
  private _inputValidation;
  private _listCategories;
  private _makeId;
  private _openEditor;
  private _onCategoryOutputsChange;
  private _pathManager;
  private _pressEnterToContinue;
  private _pushResources;
  private _storeCurrentCloudBackend;
  private _readJsonFile;
  private _removeEnvFromCloud;
  private _removeResource;
  private _sharedQuestions;
  private _showAllHelp;
  private _showHelp;
  private _showHelpfulProviderLinks;
  private _showResourceTable;
  private _serviceSelectionPrompt;
  private _updateProjectConfig;
  private _updateamplifyMetaAfterResourceUpdate;
  private _updateamplifyMetaAfterResourceAdd;
  private _updateamplifyMetaAfterResourceDelete;
  private _updateProvideramplifyMeta;
  private _updateamplifyMetaAfterPush;
  private _updateamplifyMetaAfterBuild;
  private _updateAmplifyMetaAfterPackage;
  private _updateBackendConfigAfterResourceAdd;
  private _updateBackendConfigAfterResourceUpdate;
  private _updateBackendConfigAfterResourceRemove;
  private _loadEnvResourceParameters;
  private _saveEnvResourceParameters;
  private _removeResourceParameters;
  private _removeDeploymentSecrets;
  private _triggerFlow;
  private _addTrigger;
  private _updateTrigger;
  private _deleteTrigger;
  private _deleteAllTriggers;
  private _deleteDeselectedTriggers;
  private _dependsOnBlock;
  private _getTags;
  private _getTriggerMetadata;
  private _getTriggerPermissions;
  private _getTriggerEnvVariables;
  private _getTriggerEnvInputs;
  private _getUserPoolGroupList;
  private _forceRemoveResource;
  private _writeObjectAsJson;
  private _hashDir;
  private _leaveBreadcrumbs;
  private _readBreadcrumbs;
  private _loadRuntimePlugin;
  private _getImportedAuthProperties;
  private _cleanUpTasks;
  private _invokePluginMethod?;
  private _amplifyHelpersDirPath;
  get confirmPrompt(): any;
  get constants(): any;
  get constructExeInfo(): any;
  get copyBatch(): any;
  get crudFlow(): any;
  get deleteProject(): any;
  get executeProviderUtils(): any;
  get getAllEnvs(): any;
  get getPlugin(): any;
  get getCategoryPluginInfo(): any;
  get getAllCategoryPluginInfo(): any;
  get getFrontendPlugins(): any;
  get getProviderPlugins(): any;
  get getEnvDetails(): any;
  get getEnvInfo(): () => $TSAny;
  get getPluginInstance(): any;
  get getProjectConfig(): any;
  get getProjectDetails(): () => $TSAny;
  get getProjectMeta(): () => $TSAny;
  get getResourceStatus(): any;
  get getResourceOutputs(): any;
  get getWhen(): any;
  get inputValidation(): any;
  get listCategories(): any;
  get makeId(): any;
  get openEditor(): any;
  get onCategoryOutputsChange(): any;
  get pathManager(): any;
  get pressEnterToContinue(): any;
  get pushResources(): any;
  get storeCurrentCloudBackend(): any;
  get readJsonFile(): any;
  get removeEnvFromCloud(): any;
  get removeResource(): any;
  get sharedQuestions(): any;
  get showHelp(): any;
  get showAllHelp(): any;
  get showHelpfulProviderLinks(): any;
  get showResourceTable(): any;
  get serviceSelectionPrompt(): any;
  get updateProjectConfig(): any;
  get updateamplifyMetaAfterResourceUpdate(): any;
  get updateamplifyMetaAfterResourceAdd(): any;
  get updateamplifyMetaAfterResourceDelete(): any;
  get updateProvideramplifyMeta(): any;
  get updateamplifyMetaAfterPush(): any;
  get updateamplifyMetaAfterBuild(): any;
  get updateAmplifyMetaAfterPackage(): any;
  get updateBackendConfigAfterResourceAdd(): any;
  get updateBackendConfigAfterResourceUpdate(): any;
  get updateBackendConfigAfterResourceRemove(): any;
  get loadEnvResourceParameters(): any;
  get saveEnvResourceParameters(): any;
  get removeResourceParameters(): any;
  get removeDeploymentSecrets(): any;
  get triggerFlow(): any;
  get addTrigger(): any;
  get updateTrigger(): any;
  get deleteTrigger(): any;
  get deleteAllTriggers(): any;
  get deleteDeselectedTriggers(): any;
  get dependsOnBlock(): any;
  get getTags(): any;
  get getTriggerMetadata(): any;
  get getTriggerPermissions(): any;
  get getTriggerEnvVariables(): any;
  get getTriggerEnvInputs(): any;
  get getUserPoolGroupList(): any;
  get forceRemoveResource(): any;
  get writeObjectAsJson(): any;
  get hashDir(): any;
  get leaveBreadcrumbs(): any;
  get readBreadcrumbs(): any;
  get loadRuntimePlugin(): any;
  get getImportedAuthProperties(): any;
  get invokePluginMethod(): any;
  constructor();
  addCleanUpTask: (task: (context: Context) => void) => void;
  runCleanUpTasks: (context: Context) => Promise<void>;
}
//# sourceMappingURL=amplify-toolkit.d.ts.map
